
# Copy this file to cam_purpose_config.yaml, in the same directory as this
# example file. The version of this file with the "example_" prefix will not 
# itself affect what happens to each output.
#
# Lines under to_track and to_make_avis map host names to camera numbers.
# Camera numbers listed after "default" determine what happens with output from 
# those cameras when their numbers aren't explicitly specified for a particular
# hostname.

to_track:
  default: [0, 2, 5, 6]
  hong5: [0, 1]

to_make_avis:
  default: [1, 3, 4, 7]
  hong5: [2, 3]

